### ISSUE TITLE
Structure generation

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#9]
**Feature branch: `None`**

Various individual structures will need to be generated to populate areas: the more adaptive, the better.
Structures are defined as finite objects that may be placed in an environment with little regard to topology.
See #14 for generating continuous objects

## Residence
- [ ] Inhabited cave
- [ ] ***(essential)*** Tent
- [ ] ***(essential)*** Hut
- [ ] House
- [ ] Captain's longhouse

## Transport
- [ ] Signpost
- [ ] Street lamp
- [ ] Raft
- [x] Boat
- [ ] Ship
- [ ] Cart
- [ ] Stable
- [ ] Speed beacons
- [ ] Railway stops
- [ ] Nether gateway

## Food, drink and health
- [ ] ***(essential)*** Well
- [ ] Cistern
- [ ] Trough / manger
- [ ] Apiary
- [ ] Barn
- [ ] Coop
- [ ] Fishing pier
- [ ] Hunting lodge
- [ ] Snare trap
- [ ] Granary
- [ ] Hunting lodge
- [ ] Communal oven
- [ ] ***(essential)*** Campfire
- [ ] Field kitchen
- [ ] Butcher's
- [ ] Brewery
- [ ] Public house / tavern
- [ ] Inn
- [ ] Public bath
- [ ] Infirmary
- [ ] Wisewoman's hut with herbal garden
- [ ] Regeneration beacon (in large temple?)
- [ ] Mortuary

## Defence
- [ ] ***(essential)*** Village bell
- [ ] Barricade
- [ ] Gatehouse
- [ ] Lookout tower
- [ ] Garrison's barracks
- [ ] Armory
- [ ] Weapon smithy
- [ ] Fletcher
- [ ] Strategy room with cartographer
- [ ] Iron golem cage
- [ ] Target range
- [ ] Practice dummies

## Industry
- [ ] Market stall
- [ ] Shop
- [ ] Trading post
- [ ] Warehouse
- [ ] Manual crane
- [ ] Horse mill
- [ ] Tool smithy
- [ ] Ore mill
- [ ] Felled tree
- [ ] ***(essential)*** Wood pile
- [ ] Sawmill
- [ ] Dry dock
- [ ] Masonry workshop
- [ ] Tannery
- [ ] Laundry
- [ ] ***(essential)*** General workshop

## Culture
- [ ] Shrine
- [ ] Temple
- [ ] Stone circle
- [ ] Monument
- [ ] Historian's house with library
- [ ] Stage
- [ ] Wrestling area
- [ ] Gambling den
- [ ] Festive bonfire
- [x] Burial mound

## Decoration
- [ ] Ruins
- [ ] Stone chunks / shards
- [ ] ***(essential)*** Log bench

**Comment by avdstaaij** [comment]
For now, this is out of scope of the library. To promote diversity, structure generation should be left to the users.

**Comment by avdstaaij** [comment]
Some more context on why I closed this, #10 #11, #12 and #15 (and in a sense, #1, #2, #3, #4, #5, #6, #16, and #17 as well):

In my eyes, the main purpose of this library is to provide Python bindings for the GDMC HTTP interface, and to provide all kinds of common utilities for the creation of generators in order to make programming generators as easy and accessible as possible. Pre-made generation of structures / settlements / chronicles lies out of this core scope, which is why I closed these issues for now.

It is an interesting question whether pre-made generation should eventually be included in this library, and if so, where the line should be drawn.

Positives:
- It avoids re-inventing the wheel for some common structures.
- It may make it easier for new users (generator developers) to get started.
- It makes it possible for developers to focus on higher-level settlement design, instead of specific buildings.

Negatives:
- It will likely reduce generator diversity and creativity, as users will be more likely to base their generator on the provided generation algorithms, and they will be less likely to create their own versions of the provided structures.
- It may give users the false idea that the overall style of the included generation is the "official" one.

This question should probably be answered by means of community polls and discussions with the GDMC organizers.
