### ISSUE TITLE
Support for sign block data in Minecraft 1.20

### ISSUE THREAD

**Issue by Niels-NTG** [avdstaaij/gdpc#98]
Since Minecraft 1.20 it's possible to put [text on both sides of a sign block](https://minecraft.wiki/w/Sign#Block_data). Same is true for the new hanging sign blocks also added in this update.

To accommodate this the NBT data structure of signs has changed

Here's an example of a sign in Minecraft 1.20.2
```nbt
back_text: {
   color: "black",
   has_glowing_text: 0b,
   messages: ['{\"text\":\"flipside text 1\"}','{\"text\":\"flipside text 2\"}','{\"text\":\"flipside text 3\"}','{\"text\":\"flipside text 4\"}']
},
front_text: {
   color: "black",
   has_glowing_text: 0b,
   messages: ['{\"text\":\"some text 1\"}','{\"text\":\"some text 2\"}','{\"text\":\"some text 3\"}','{\"text\":\"some text 4\"}']
},
is_waxed: 0b
```

When using the `POST /structure` endpoint in GDMC-HTTP any data posted that has a `DataVersion` attribute included (which should be included with any `.nbt` file), Minecraft automatically applies its "data fixer" functions that update the data to something that works with current version of Minecraft. I've tried to incorporate this into the `PUT /blocks` endpoint as well but without success. And besides, even if it that worked it would still require users to supply the `DataVersion` of the original data (eg. from a version before 1.20) so that Minecraft understands what data needs fixing before placing it into the world.

Since this by my knowledge is the only major thing that has changed in data structure of an existing block I think we can instead update the sign-making util function in GDPC that switches behavior depending on the known `DataVersion` or Minecraft version, which can be retrieved using the `GET /version` or `OPTIONS /` endpoints.

**Comment by avdstaaij** [comment]
This is actually a small example of a problem that I believe to be a bit more involved and fundamental than it may initially seem. I'll write a more detailed response later.

**Comment by avdstaaij** [comment]
So, the problem I was referring to is supporting multiple versions of Minecraft simultaneously (for example via a switch on `GET /version` like you describe). As it turns out, I had so much to say about this that I decided it would be better to make a separate issue for it: #99

As I explain there in perhaps too many words, I believe there is unfortunately little use to supporting multiple versions of Minecraft in utility functions like the sign helpers unless a whole lot of other stuff is done first. In the short term, I think we should just update the sign helpers to the new format (with no old format support).

**Comment by avdstaaij** [comment]
I implemented the short-term solution of just switching to the new format. We can continue discussion about supporting multiple Minecraft versions simultaneously in #99.
